/**
 * Blog Image URL Mapping
 * Maps blog post slugs to their AI-generated image URLs in Vercel Blob
 * Auto-generated by scripts/generate-blog-images.ts
 * Last updated: 2026-05-09T04:44:09.319Z
 */

// Generated image URLs stored in Vercel Blob
// Key: post slug, Value: blob URL
export const generatedImageUrls: Record<string, string> = {
  "questioning-boutique-digital-marketing-agency": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/questioning-boutique-digital-marketing-agency.jpg",
  "why-dc-clients-arent-finding-you-on-digital": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/why-dc-clients-arent-finding-you-on-digital.jpg",
  "how-to-detect-hosting-is-hurting-conversion": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/how-to-detect-hosting-is-hurting-conversion.jpg",
  "tips-for-choosing-a-wordpress-development-agency": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/tips-for-choosing-a-wordpress-development-agency.jpg",
  "launching-managed-web-host-setup": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/launching-managed-web-host-setup.jpg",
  "gaps-in-your-digital-marketing-strategy": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/gaps-in-your-digital-marketing-strategy.jpg",
  "ad-spending-for-nonprofits-in-washington-dc": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/ad-spending-for-nonprofits-in-washington-dc.jpg",
  "wordpress-agency-slowing-site-down": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/wordpress-agency-slowing-site-down.jpg",
  "guide-to-managing-hosting-headaches-during-site-upgrades": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/guide-to-managing-hosting-headaches-during-site-upgrades.jpg",
  "why-website-leads-vanish": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/why-website-leads-vanish.jpg",
  "why-boutique-marketing-agencies-misuse-ai": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/why-boutique-marketing-agencies-misuse-ai.jpg",
  "how-to-avoid-diy-web-maintenance": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/how-to-avoid-diy-web-maintenance.jpg",
  "fixing-ad-account-bloat-in-your-linkedin-campaigns": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/fixing-ad-account-bloat-in-your-linkedin-campaigns.jpg",
  "case-hiring-fractional-cmo-right-now": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/case-hiring-fractional-cmo-right-now.jpg",
  "good-encryption-isnt-tech-team-job-anymore": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/good-encryption-isnt-tech-team-job-anymore.jpg",
  "guide-integrated-digital-strategy-small-teams": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/guide-integrated-digital-strategy-small-teams.jpg",
  "understanding-demand-generation-campaigns-stalling": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/understanding-demand-generation-campaigns-stalling.jpg",
  "steps-clean-up-old-site-data-before-seo-work": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/steps-clean-up-old-site-data-before-seo-work.jpg",
  "why-social-media-ad-spend-isnt-returning-leads": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/why-social-media-ad-spend-isnt-returning-leads.jpg",
  "pick-managed-wordpress-hosting-setup-doesnt-break": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/pick-managed-wordpress-hosting-setup-doesnt-break.jpg",
  "social-media-ads-arent-converting-and-how-to-fix-it": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/social-media-ads-arent-converting-and-how-to-fix-it.jpg",
  "solving-content-distribution-problems-for-multi-channel-marketing": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/solving-content-distribution-problems-for-multi-channel-marketing.jpg",
  "dc-business-isnt-showing-up-local-searches": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/dc-business-isnt-showing-up-local-searches.jpg",
  "ai-marketing-problems-prepare-2026": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/ai-marketing-problems-prepare-2026.jpg",
  "fixing-frustrating-wordpress-errors-managed-hosting": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/fixing-frustrating-wordpress-errors-managed-hosting.jpg",
  "ppc-campaigns-wasting-money-stop": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/ppc-campaigns-wasting-money-stop.jpg",
  "holiday-marketing-problems-solved-with-timely-digital-strategies": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/holiday-marketing-problems-solved-with-timely-digital-strategies.jpg",
  "fix-outdated-website-design-without-starting-over": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/fix-outdated-website-design-without-starting-over.jpg",
  "using-ai-fix-declining-engagement-rates-content-marketing": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/using-ai-fix-declining-engagement-rates-content-marketing.jpg",
  "solving-wordpress-speed-issues-specialized-managed-hosting": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/solving-wordpress-speed-issues-specialized-managed-hosting.jpg",
  "why-your-marketing-channels-arent-working-together-and-how-to-fix-it": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/why-your-marketing-channels-arent-working-together-and-how-to-fix-it.jpg",
  "troubleshooting-failed-linkedin-ad-campaigns-benchmark-data": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/troubleshooting-failed-linkedin-ad-campaigns-benchmark-data.jpg",
  "solving-brand-inconsistency-issues-with-digital-integration": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/solving-brand-inconsistency-issues-with-digital-integration.jpg",
  "overcoming-donor-engagement-challenges-for-dc-nonprofits-online": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/overcoming-donor-engagement-challenges-for-dc-nonprofits-online.jpg",
  "stop-website-loading-problems-better-web-hosting": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/stop-website-loading-problems-better-web-hosting.jpg",
  "fixing-customer-targeting-issues-ai-powered-segmentation": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/fixing-customer-targeting-issues-ai-powered-segmentation.jpg",
  "what-to-do-wordpress-site-crashes-hosting-solutions": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/what-to-do-wordpress-site-crashes-hosting-solutions.jpg",
  "local-seo-problems-dc-small-businesses-face-and-how-to-solve-them": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/local-seo-problems-dc-small-businesses-face-and-how-to-solve-them.jpg",
  "rebuild-when-optimize-wordpress-website": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/rebuild-when-optimize-wordpress-website.jpg",
  "breaking-down-silos-marketing-integrated-strategy": "https://yd7xw8j43d5hdlrd.public.blob.vercel-storage.com/blog-images/breaking-down-silos-marketing-integrated-strategy.jpg"
};

/**
 * Get the image URL for a blog post
 * Returns the AI-generated image if available, otherwise returns the fallback
 */
export function getBlogImageUrl(slug: string, fallbackUrl: string): string {
  return generatedImageUrls[slug] || fallbackUrl;
}

/**
 * Check if a post has a generated image
 */
export function hasGeneratedImage(slug: string): boolean {
  return slug in generatedImageUrls;
}

/**
 * Get all posts that have generated images
 */
export function getPostsWithGeneratedImages(): string[] {
  return Object.keys(generatedImageUrls);
}

/**
 * Get count of generated images
 */
export function getGeneratedImageCount(): number {
  return Object.keys(generatedImageUrls).length;
}
