/**
 * Batch Blog Image Generation Script
 *
 * Generates AI images for all blog posts and stores them in Vercel Blob.
 * Updates the blog-image-urls.ts file with the generated URLs.
 *
 * Usage: npx tsx scripts/generate-blog-images.ts
 *
 * Environment variables required:
 * - FAL_KEY: fal AI API key
 * - BLOB_READ_WRITE_TOKEN: Vercel Blob token
 */

import * as fal from "@fal-ai/serverless-client";
import { put, list } from "@vercel/blob";
import { writeFileSync, readFileSync } from "fs";
import { blogPosts } from "../lib/blog-data";
import {
  generateQuickPrompt,
  getDetectedBrands,
} from "../lib/blog-image-prompt";

// Configure fal client
fal.config({
  credentials: process.env.FAL_KEY,
});

// Rate limiting settings
const DELAY_BETWEEN_REQUESTS = 2000; // 2 seconds between requests
const MAX_RETRIES = 3;

// Track generated images
const generatedUrls: Record<string, string> = {};

/**
 * Sleep utility for rate limiting
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Check if an image already exists in blob storage
 */
async function checkExistingImage(slug: string): Promise<string | null> {
  try {
    const { blobs } = await list({ prefix: `blog-images/${slug}` });
    if (blobs.length > 0) {
      return blobs[0].url;
    }
  } catch (error) {
    // Blob doesn't exist
  }
  return null;
}

/**
 * Generate image for a single blog post
 */
async function generateImageForPost(
  post: (typeof blogPosts)[0],
  retryCount = 0
): Promise<string | null> {
  try {
    const prompt = generateQuickPrompt(post);
    const brands = getDetectedBrands(post);

    console.log(`  Prompt: ${prompt.substring(0, 100)}...`);
    if (brands.length > 0) {
      console.log(`  Detected brands: ${brands.join(", ")}`);
    }

    // Generate image using fal AI
    const result = await fal.subscribe("fal-ai/flux/schnell", {
      input: {
        prompt,
        image_size: "landscape_16_9",
        num_inference_steps: 4,
        num_images: 1,
      },
    });

    const falImageUrl = (result as { images?: { url: string }[] }).images?.[0]
      ?.url;

    if (!falImageUrl) {
      throw new Error("No image generated");
    }

    // Fetch and upload to Vercel Blob
    const imageResponse = await fetch(falImageUrl);
    if (!imageResponse.ok) {
      throw new Error("Failed to fetch generated image");
    }

    const imageBuffer = await imageResponse.arrayBuffer();

    const blob = await put(`blog-images/${post.slug}.jpg`, imageBuffer, {
      access: "public",
      contentType: "image/jpeg",
    });

    console.log(`  Uploaded to: ${blob.url}`);
    return blob.url;
  } catch (error) {
    console.error(
      `  Error: ${error instanceof Error ? error.message : "Unknown error"}`
    );

    if (retryCount < MAX_RETRIES) {
      console.log(`  Retrying (${retryCount + 1}/${MAX_RETRIES})...`);
      await sleep(5000); // Wait 5 seconds before retry
      return generateImageForPost(post, retryCount + 1);
    }

    return null;
  }
}

/**
 * Update the blog-image-urls.ts file with generated URLs
 */
function updateUrlsFile(urls: Record<string, string>): void {
  const content = `/**
 * Blog Image URL Mapping
 * Maps blog post slugs to their AI-generated image URLs in Vercel Blob
 * Auto-generated by scripts/generate-blog-images.ts
 * Last updated: ${new Date().toISOString()}
 */

// Generated image URLs stored in Vercel Blob
// Key: post slug, Value: blob URL
export const generatedImageUrls: Record<string, string> = ${JSON.stringify(urls, null, 2)};

/**
 * Get the image URL for a blog post
 * Returns the AI-generated image if available, otherwise returns the fallback
 */
export function getBlogImageUrl(slug: string, fallbackUrl: string): string {
  return generatedImageUrls[slug] || fallbackUrl;
}

/**
 * Check if a post has a generated image
 */
export function hasGeneratedImage(slug: string): boolean {
  return slug in generatedImageUrls;
}

/**
 * Get all posts that have generated images
 */
export function getPostsWithGeneratedImages(): string[] {
  return Object.keys(generatedImageUrls);
}

/**
 * Get count of generated images
 */
export function getGeneratedImageCount(): number {
  return Object.keys(generatedImageUrls).length;
}
`;

  writeFileSync("./lib/blog-image-urls.ts", content);
  console.log(`\nUpdated lib/blog-image-urls.ts with ${Object.keys(urls).length} image URLs`);
}

/**
 * Main batch generation function
 */
async function main() {
  console.log("===========================================");
  console.log("Blog Image Batch Generation Script");
  console.log("===========================================\n");

  // Check environment variables
  if (!process.env.FAL_KEY) {
    console.error("Error: FAL_KEY environment variable is required");
    process.exit(1);
  }

  if (!process.env.BLOB_READ_WRITE_TOKEN) {
    console.error("Error: BLOB_READ_WRITE_TOKEN environment variable is required");
    process.exit(1);
  }

  console.log(`Total posts to process: ${blogPosts.length}\n`);

  // Load existing URLs if available
  try {
    const existingContent = readFileSync("./lib/blog-image-urls.ts", "utf-8");
    const match = existingContent.match(/export const generatedImageUrls[^=]*=\s*({[\s\S]*?});/);
    if (match) {
      const existingUrls = JSON.parse(match[1].replace(/'/g, '"'));
      Object.assign(generatedUrls, existingUrls);
      console.log(`Loaded ${Object.keys(generatedUrls).length} existing image URLs\n`);
    }
  } catch {
    console.log("No existing URLs file found, starting fresh\n");
  }

  let processed = 0;
  let generated = 0;
  let skipped = 0;
  let failed = 0;

  for (const post of blogPosts) {
    processed++;
    console.log(`[${processed}/${blogPosts.length}] Processing: ${post.title.substring(0, 50)}...`);

    // Check if already generated
    if (generatedUrls[post.slug]) {
      console.log("  Already has generated image, skipping");
      skipped++;
      continue;
    }

    // Check if exists in blob storage
    const existingUrl = await checkExistingImage(post.slug);
    if (existingUrl) {
      console.log("  Found existing image in blob storage");
      generatedUrls[post.slug] = existingUrl;
      skipped++;
      continue;
    }

    // Generate new image
    const imageUrl = await generateImageForPost(post);

    if (imageUrl) {
      generatedUrls[post.slug] = imageUrl;
      generated++;
    } else {
      failed++;
    }

    // Rate limiting
    await sleep(DELAY_BETWEEN_REQUESTS);

    // Save progress periodically
    if (generated % 10 === 0) {
      updateUrlsFile(generatedUrls);
    }
  }

  // Final save
  updateUrlsFile(generatedUrls);

  console.log("\n===========================================");
  console.log("Generation Complete!");
  console.log("===========================================");
  console.log(`Total processed: ${processed}`);
  console.log(`Newly generated: ${generated}`);
  console.log(`Skipped (existing): ${skipped}`);
  console.log(`Failed: ${failed}`);
  console.log(`Total images available: ${Object.keys(generatedUrls).length}`);
}

main().catch(console.error);
